#!/usr/bin/env bash
set -euo pipefail

STAGED_GO=$(git diff --cached --name-only --diff-filter=ACM -- 'server/**/*.go' 'server/*.go' || true)
STAGED_GD=$(git diff --cached --name-only --diff-filter=ACM -- 'client/**/*.gd' 'client/*.gd' || true)

if [ -n "$STAGED_GO" ]; then
  nix develop --command bash -c "just server lint"
  nix develop --command bash -c "just server test"
  nix develop --command bash -c "just server fmt"
fi

if [ -n "$STAGED_GD" ]; then
  nix develop --command bash -c "just client check"
  nix develop --command bash -c "just client test"
  nix develop --command bash -c "just client fmt"
fi
