{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyrrhic-stars.secretName" . }}
  labels:
    {{- include "pyrrhic-stars.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DSN: {{ .Values.config.postgres.dsn | quote }}
  {{- if .Values.config.clickhouse.addr }}
  CLICKHOUSE_PASSWORD: {{ .Values.config.clickhouse.password | quote }}
  {{- end }}
{{- end }}
