root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/chat ./cmd/chat/"
  bin = "./tmp/chat"
  include_ext = ["go", "mod", "sum"]
  exclude_dir = ["tmp", ".go"]
  delay = 500
  poll = true
  poll_interval = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
